name: ai_learn_pulse
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  pinput: ^5.0.0
  top_snackbar_flutter: ^3.1.0
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.1
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  dio: ^5.7.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  get_storage: ^2.1.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/app_icons/
    - assets/app_images/
    - assets/colors/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
